### ISSUE TITLE
margin

### ISSUE THREAD

**Issue by guer0125** [guer0125/modularity-mindfulness#1]
Hey,

i'm having a problem with where my P and A tag are in the articles. the margins are overlapping. i have to add double margin to actually create a space. do you know how i can fix that? 

thank you

@HannahDelaney

**Comment by HannahDelaney** [comment]
I'm not sure exactly what you mean by overlapping, is it that the spacing between the `<p>` and `<a>` tags is uneven? You should be able to add the same `margin-bottom` value to them all, and then give your `<a>` articles a `margin-top: auto;` which will allow the browser to calculate the space for you. It should even them out.

I hope that's what you meant?

**Comment by guer0125** [comment]
it's hard to explain here. but even though i had a margin-bottom:1rem; in my <p> the <p> was on top of my <a>. touching each other. so  i have to do a double margin margin-bottom: 2rem; and doing this would make it look like 1rem because the other 1 rem would overlap. i hope it makes sense

**Comment by guer0125** [comment]
i figures out my small screen, im still having trouble with my medium,  how can i place each of my articles in the different columns? i'm trying to do the same thing as last assignment  but it's not working

**Comment by HannahDelaney** [comment]
Hm, okay. I'm still not sure about the margin error, but part of the trouble you're having with setting up the 3 columns is that you've added the grid to the body of the code, so it's adding a bunch of space for the extra rows and applying everywhere vs the specific place you want. Try changing it to target the `section`.

You've got a huge chunk of space between your pieces here because you have defined `grid-template-rows: 1fr 1fr:`, so it is spacing things out massively on the vertical of the entire body. Once it's moved to the section there will be a big space at just the bottom, so you can change that to `grid-template-rows: 1fr;`, or just get rid of it altogether.

Hopefully that pushes you in the right direction!

**Comment by guer0125** [comment]
could you guide me in the right direction to move rock garden and nav up?

thank you

**Comment by HannahDelaney** [comment]
Noticed Chelle addressed this on your other issue. Let she or I know if it doesn't work! And if it does don't forget to close both of the issues :)

**Comment by guer0125** [comment]
yes it worked, not im working on my margins/paddings to match them. any suggestions?
